### ISSUE TITLE
terraformGateway --help switch requires ATLAS_USERNAME to be set

### ISSUE THREAD

**Issue by robinbowes** [PlethoraOfHate/tf_api_gateway#4]
Running `terraformGateway --help` throws this traceback:

```
Traceback (most recent call last):
  File "/Users/robin/.pyenv/versions/td-terraform-3.7.1/bin/terraformGateway", line 56, in <module>
    @click.option('--organization', default=os.environ['ATLAS_USERNAME'], help='Terraform Organization name (Uses ATLAS_USERNAME environment var if not provided)')
  File "/Users/robin/.pyenv/versions/3.7.1/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'ATLAS_USERNAME'
```

**Comment by robinbowes** [comment]
It works OK if `ATLAS_USERNAME` is set when running the command:

```
ATLAS_USERNAME=robinbowes terraformGateway --help
Usage: terraformGateway [OPTIONS] COMMAND [ARGS]...

  Console utility for interfacing with Terraform Enterprise

  To see details for each command, use:
   terraformGateway [command] --help
...
```

**Comment by robinbowes** [comment]
I didn't mean to close this. I only said "should fix" not "does fix" !!
